#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("F2S.MvvmX.Glass.LiveCardApiDemo.Droid.Resource", IsApplication=true)]

namespace F2S.MvvmX.Glass.LiveCardApiDemo.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::F2S.MvvmX.Plugins.TextToSpeech.Droid.Resource.String.ApplicationName = global::F2S.MvvmX.Glass.LiveCardApiDemo.Droid.Resource.String.ApplicationName;
			global::F2S.MvvmX.Plugins.TextToSpeech.Droid.Resource.String.Hello = global::F2S.MvvmX.Glass.LiveCardApiDemo.Droid.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0a0000
			public const int direction_abbreviations = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int spoken_directions = 2131361793;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int card_margin = 2131165184;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int gradient50 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_compass = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_read_aloud = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_stop = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int place_mark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int splash = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int LivecardContent = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int MvxBindingTagUnique = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int Stop = 2131230727;
			
			// aapt resource value: 0x7f080001
			public const int compass = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int read_aloud = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int stop = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int tips_container = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int tips_view = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int compass = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DummyCard = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FirstView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SplashScreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ViewMapNotFound = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int compass = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int DummyMenu = 2131427329;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int landmarks = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int glass_voice_trigger = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int magnetic_interference = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int pitch_too_steep = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int place_text_format = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int read_aloud = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int spoken_heading_format = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int spoken_heading_format_one = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int stop = 2131099657;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090001
			public const int MenuTheme = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int Theme_Invisible = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int Theme_Splash = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int voicetriggerstart = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
