#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("F2S.TinyMvx.Glass.Demo.Resource", IsApplication=true)]

namespace F2S.TinyMvx.Glass.Demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::F2S.TinyMvx.Glass.Demo.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::F2S.TinyMvx.Glass.Demo.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::F2S.TinyMvx.Glass.Demo.Resource.Layout.zxingscannerfragmentlayout;
			global::F2S.TinyMvx.Glass.QR.Resource.Attribute.fontWeight = global::F2S.TinyMvx.Glass.Demo.Resource.Attribute.fontWeight;
			global::F2S.TinyMvx.Glass.QR.Resource.Attribute.id = global::F2S.TinyMvx.Glass.Demo.Resource.Attribute.id;
			global::F2S.TinyMvx.Glass.QR.Resource.Attribute.image = global::F2S.TinyMvx.Glass.Demo.Resource.Attribute.image;
			global::F2S.TinyMvx.Glass.QR.Resource.Attribute.isDefaultItem = global::F2S.TinyMvx.Glass.Demo.Resource.Attribute.isDefaultItem;
			global::F2S.TinyMvx.Glass.QR.Resource.Attribute.name = global::F2S.TinyMvx.Glass.Demo.Resource.Attribute.name;
			global::F2S.TinyMvx.Glass.QR.Resource.Attribute.tip = global::F2S.TinyMvx.Glass.Demo.Resource.Attribute.tip;
			global::F2S.TinyMvx.Glass.QR.Resource.Dimension.between_icon_text_padding = global::F2S.TinyMvx.Glass.Demo.Resource.Dimension.between_icon_text_padding;
			global::F2S.TinyMvx.Glass.QR.Resource.Dimension.qr_scan_text_bottom_padding = global::F2S.TinyMvx.Glass.Demo.Resource.Dimension.qr_scan_text_bottom_padding;
			global::F2S.TinyMvx.Glass.QR.Resource.Dimension.small_text_size = global::F2S.TinyMvx.Glass.Demo.Resource.Dimension.small_text_size;
			global::F2S.TinyMvx.Glass.QR.Resource.Drawable.qr_code_footer = global::F2S.TinyMvx.Glass.Demo.Resource.Drawable.qr_code_footer;
			global::F2S.TinyMvx.Glass.QR.Resource.Drawable.qr_code_scan_frame = global::F2S.TinyMvx.Glass.Demo.Resource.Drawable.qr_code_scan_frame;
			global::F2S.TinyMvx.Glass.QR.Resource.Id.black = global::F2S.TinyMvx.Glass.Demo.Resource.Id.black;
			global::F2S.TinyMvx.Glass.QR.Resource.Id.bold = global::F2S.TinyMvx.Glass.Demo.Resource.Id.bold;
			global::F2S.TinyMvx.Glass.QR.Resource.Id.condensed = global::F2S.TinyMvx.Glass.Demo.Resource.Id.condensed;
			global::F2S.TinyMvx.Glass.QR.Resource.Id.contentFrame = global::F2S.TinyMvx.Glass.Demo.Resource.Id.contentFrame;
			global::F2S.TinyMvx.Glass.QR.Resource.Id.italic = global::F2S.TinyMvx.Glass.Demo.Resource.Id.italic;
			global::F2S.TinyMvx.Glass.QR.Resource.Id.label = global::F2S.TinyMvx.Glass.Demo.Resource.Id.label;
			global::F2S.TinyMvx.Glass.QR.Resource.Id.light = global::F2S.TinyMvx.Glass.Demo.Resource.Id.light;
			global::F2S.TinyMvx.Glass.QR.Resource.Id.medium = global::F2S.TinyMvx.Glass.Demo.Resource.Id.medium;
			global::F2S.TinyMvx.Glass.QR.Resource.Id.overlay = global::F2S.TinyMvx.Glass.Demo.Resource.Id.overlay;
			global::F2S.TinyMvx.Glass.QR.Resource.Id.regular = global::F2S.TinyMvx.Glass.Demo.Resource.Id.regular;
			global::F2S.TinyMvx.Glass.QR.Resource.Id.thin = global::F2S.TinyMvx.Glass.Demo.Resource.Id.thin;
			global::F2S.TinyMvx.Glass.QR.Resource.Layout.QRScan = global::F2S.TinyMvx.Glass.Demo.Resource.Layout.QRScan;
			global::F2S.TinyMvx.Glass.QR.Resource.Layout.zxingscanneractivitylayout = global::F2S.TinyMvx.Glass.Demo.Resource.Layout.zxingscanneractivitylayout;
			global::F2S.TinyMvx.Glass.QR.Resource.Layout.zxingscannerfragmentlayout = global::F2S.TinyMvx.Glass.Demo.Resource.Layout.zxingscannerfragmentlayout;
			global::F2S.TinyMvx.Glass.QR.Resource.String.ApplicationName = global::F2S.TinyMvx.Glass.Demo.Resource.String.ApplicationName;
			global::F2S.TinyMvx.Glass.QR.Resource.String.Hello = global::F2S.TinyMvx.Glass.Demo.Resource.String.Hello;
			global::F2S.TinyMvx.Glass.QR.Resource.String.qr_scan_tips = global::F2S.TinyMvx.Glass.Demo.Resource.String.qr_scan_tips;
			global::F2S.TinyMvx.Glass.QR.Resource.Style.OverlayText = global::F2S.TinyMvx.Glass.Demo.Resource.Style.OverlayText;
			global::F2S.TinyMvx.Glass.QR.Resource.Style.SmallOverlayText = global::F2S.TinyMvx.Glass.Demo.Resource.Style.SmallOverlayText;
			global::F2S.TinyMvx.Glass.Resource.String.ApplicationName = global::F2S.TinyMvx.Glass.Demo.Resource.String.ApplicationName;
			global::F2S.TinyMvx.Glass.Resource.String.Hello = global::F2S.TinyMvx.Glass.Demo.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int fontWeight = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int id = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int image = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int isDefaultItem = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int name = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int tip = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060001
			public const int between_icon_text_padding = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int qr_scan_text_bottom_padding = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int small_text_size = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bingdesktop = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bleu1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bleu2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bleu3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bleu4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bleu5 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int braque899 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int gradient50 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_compass = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_read_aloud = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_stop = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int place_mark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int qr_code_footer = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int qr_code_scan_frame = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int qrcode = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int splash = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050008
			public const int MyButton = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int black = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int bold = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int condensed = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int contentFrame = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int italic = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int label = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int light = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int medium = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int overlay = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int regular = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int thin = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int QRScan = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int zxingscanneractivitylayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int zxingscannerfragmentlayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int qr_scan_tips = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int OverlayText = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int SmallOverlayText = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
