#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("F2S.TinyMvx.Glass.QR.Resource", IsApplication=false)]

namespace F2S.TinyMvx.Glass.QR
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int fontWeight = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int id = 2130771969;
			
			// aapt resource value: 0x7f010003
			public static int image = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int isDefaultItem = 2130771972;
			
			// aapt resource value: 0x7f010002
			public static int name = 2130771970;
			
			// aapt resource value: 0x7f010005
			public static int tip = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060001
			public static int between_icon_text_padding = 2131099649;
			
			// aapt resource value: 0x7f060002
			public static int qr_scan_text_bottom_padding = 2131099650;
			
			// aapt resource value: 0x7f060000
			public static int small_text_size = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int qr_code_footer = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int qr_code_scan_frame = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public static int black = 2131034117;
			
			// aapt resource value: 0x7f050004
			public static int bold = 2131034116;
			
			// aapt resource value: 0x7f050007
			public static int condensed = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public static int contentFrame = 2131034122;
			
			// aapt resource value: 0x7f050006
			public static int italic = 2131034118;
			
			// aapt resource value: 0x7f050009
			public static int label = 2131034121;
			
			// aapt resource value: 0x7f050002
			public static int light = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int medium = 2131034115;
			
			// aapt resource value: 0x7f050008
			public static int overlay = 2131034120;
			
			// aapt resource value: 0x7f050000
			public static int regular = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int thin = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int QRScan = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int zxingscanneractivitylayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int zxingscannerfragmentlayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public static int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public static int qr_scan_tips = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public static int OverlayText = 2131165184;
			
			// aapt resource value: 0x7f070001
			public static int SmallOverlayText = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
