#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("F2S.Glass.Spikes.ApiDemo.Resource", IsApplication=true)]

namespace F2S.Glass.Spikes.ApiDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::F2S.Glass.Framework.Resource.String.ApplicationName = global::F2S.Glass.Spikes.ApiDemo.Resource.String.ApplicationName;
			global::F2S.Glass.Framework.Resource.String.Hello = global::F2S.Glass.Spikes.ApiDemo.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int card_generic_padding = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int menu_icon_margin = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int menu_icon_size = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int menu_text_size = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int slider_bar_height = 2131099652;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bar_candy0000 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bar_candy0001 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bar_candy0002 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bar_candy0003 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bar_candy0004 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bar_candy0005 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bar_candy0006 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bar_candy0007 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bar_candy0008 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bar_candy0009 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bar_candy0010 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bar_candy0011 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bar_candy0012 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bar_candy0013 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int bar_candy0014 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int bar_candy0015 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int bar_candy0016 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int bar_candy0017 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int bar_candy0018 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int bar_candy0019 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int bar_candy0020 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int bar_candy0021 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int bar_candy0022 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int bar_candy0023 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int bar_candy0024 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int bar_candy0025 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int bar_candy0026 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int bar_candy0027 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int bar_candy0028 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int bar_candy0029 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int bar_candy0030 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int bar_candy0031 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int bar_candy0032 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int bar_candy0033 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int bar_candy0034 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int bar_candy0035 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int bar_candy0036 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int bar_candy0037 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int bar_candy0038 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int bar_candy0039 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int bar_candy0040 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int bar_candy0041 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int bar_candy0042 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int bar_candy0043 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int bar_candy0044 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int bar_candy0045 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int bar_candy0046 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int bar_candy0047 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int bar_candy0048 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int bar_candy0049 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int bar_candy0050 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int bar_candy0051 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int bar_candy0052 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int bar_candy0053 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int bar_candy0054 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int bar_candy0055 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int bar_candy0056 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int bar_candy0057 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int bar_candy0058 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int bar_candy0059 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int bleu1 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int bleu2 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int bleu3 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int bleu4 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int bleu5 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int Icon = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int progress_bar_determinate = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int slider_indeterminate = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int star = 2130837572;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int MyButton = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int icon = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int indeterminate_slider = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int label = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int slider = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int slider_control = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080001
			public const int horizontal_scroll_deferred_load_animation_duration_ms = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int horizontal_scroll_deferred_sizing_animation_duration_ms = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int slider_in_out_animation_duration_ms = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int slider = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int MenuTheme = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int VoiceTriggerStart = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
