#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("F2S.Glass.ApiDemo.Resource", IsApplication=true)]

namespace F2S.Glass.ApiDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::F2S.Glass.ApiDemo.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::F2S.Glass.ApiDemo.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::F2S.Glass.ApiDemo.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050007
			public const int dark_green = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int dark_red = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int dark_yellow = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int divider_color = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int green = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int red = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int touchpad_background_color = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int yellow = 2131034116;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int card_margin = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int table_divider_height = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int table_divider_margin = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bleu1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bleu2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bleu3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bleu4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bleu5 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int braque899 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int finger_trace_0 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int finger_trace_1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int finger_trace_2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080007
			public const int MyButton = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int contentFrame = 2131230728;
			
			// aapt resource value: 0x7f080003
			public const int divider1 = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int finger_count = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int finger_count_label = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int last_gesture = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int last_gesture_label = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int swipe_again_tip = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int touchpad = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_discrete_gestures = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int zxingscanneractivitylayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int zxingscannerfragmentlayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int delta = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int displacement = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int finger_count = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int glass_voice_trigger = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int last_gesture = 2131165190;
			
			// aapt resource value: 0x7f07000e
			public const int pixel_distance_units = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int pixel_velocity_units = 2131165199;
			
			// aapt resource value: 0x7f07000c
			public const int scroll_one_finger = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int scroll_two_finger = 2131165197;
			
			// aapt resource value: 0x7f070008
			public const int scrolling = 2131165192;
			
			// aapt resource value: 0x7f070010
			public const int swipe_down_again = 2131165200;
			
			// aapt resource value: 0x7f070002
			public const int text_cards = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int text_gesture_detector = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int text_theming = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int velocity = 2131165195;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int voicetriggerstart = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
